#! /bin/sh

xrandr --output HDMI1 --primary &
xrandr --output eDP1 --off &
xrandr --output DP2 --off &

feh --bg-fill $HOME/.wallpapers/wall1.jpg

sxhkd &
compton &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           3

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true
